//
// This file was generated by the Retargetable Decompiler
// Website: http://decompiler.fit.vutbr.cz
// Copyright (c) 2011-2014 Lissom <decompiler@fit.vutbr.cz>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

/* ------------- Structures ------------- */

struct struct__IO_FILE {
    int32_t e0;
    int8_t * e1;
    int8_t * e2;
    int8_t * e3;
    int8_t * e4;
    int8_t * e5;
    int8_t * e6;
    int8_t * e7;
    int8_t * e8;
    int8_t * e9;
    int8_t * e10;
    int8_t * e11;
    struct struct__IO_marker * e12;
    struct struct__IO_FILE * e13;
    int32_t e14;
    int32_t e15;
    int32_t e16;
    int16_t e17;
    int8_t e18;
    int8_t e19[1];
    int8_t * e20;
    int64_t e21;
    int8_t * e22;
    int8_t * e23;
    int8_t * e24;
    int8_t * e25;
    int32_t e26;
    int32_t e27;
    int8_t e28[40];
};

struct struct__IO_marker {
    struct struct__IO_marker * e0;
    struct struct__IO_FILE * e1;
    int32_t e2;
};

/* -------- Function Prototypes --------- */

int32_t do_magic(int8_t * a1, int32_t result);
int32_t magic(void);

/* ------------- Functions -------------- */

int32_t do_magic(int8_t * a1, int32_t result) {
    // 0x8048621
    srand(time(NULL));
    if (result <= 0) {
        // 0x804867a
        return 0;
    }
    int32_t v1 = 0;
    int32_t v2 = v1 + (int32_t)a1; // 0x804864c
    int32_t v3 = (int32_t)*(int8_t *)v2;
    *(int8_t *)v2 = (int8_t)(v3 ^ rand());
    // branch -> 0x8048646
    while (v1 + 1 != result) {
        // 0x8048646
        v1++;
        v2 = v1 + (int32_t)a1;
        v3 = (int32_t)*(int8_t *)v2;
        *(int8_t *)v2 = (int8_t)(v3 ^ rand());
        // continue -> 0x8048646
    }
    // 0x804867a
    return result;
}

int32_t magic(void) {
    // 0x8048681
    int8_t * str;
    scanf("%s", str);
    do_magic(str, strlen(str));
    return printf("%s", str);
}

int main(int argc, char **argv) {
    // bb
    puts("Welcome to Magic system!");
    printf("Give me your name(a-z): ");
    fflush(NULL);
    int32_t v1 = 0;
    // branch -> 0x8048701
    int8_t * buf;
    while (v1 < 10 & ((read(0, buf, 1) == 0 || buf < (int8_t *)97 || buf > (int8_t *)122) ^ true)) {
        // 0x8048701
        v1++;
        // continue -> 0x8048701
    }
    // 0x8048757
    printf("Your name is %s.\n", buf);
    printf("Give me something that you want to MAGIC: ");
    fflush(NULL);
    magic();
    return 0;
}

/* --------- External Functions --------- */

// int fflush (FILE *)
// int printf (const char *restrict, ...)
// int puts (const char *)
// int rand ()
// ssize_t read(int fildes, void *buf, size_t nbyte)
// int scanf (const char *restrict, ...)
// void srand (unsigned int)
// size_t strlen (const char *)
// time_t time(time_t *tloc)

/* ---------- Meta-Information ---------- */

// Detected compiler: llvm (i686-pc-linux-gnu) 3.2
// Detected functions: 3 (3 in front-end)
// Decompiler release: v1.7 (Jun 30 2014)
// Decompilation date: Sep 29 2014 17:24:03
